### ISSUE TITLE
datetime64 Timestamp conversion

### ISSUE THREAD

**Issue by tvasyleva** [bsnacks000/binx#3]
converting to and from df->collection breaks dateTime parsing

**Comment by bsnacks000** [comment]
Probably have to do something like this:
given input as : 
```df = pd.DataFrame({'a':[pd.Timestamp(2017,1,1,12), pd.Timestamp(2017, 1, 1, 1)]})```

we wrap this in a utility method that gets called in load_data: 
```df['a'] = df['a'].dt.strftime('%Y-%m-%d %H:%M:%S')```
Marshmallow date and datetime fields should be able to accept that

It would be good for the utility method to figure out a way to infer the timestamp format for date cols... not sure if this could easily be done. Otherwise the user would need to pass in a dict with the cols that need to be formatted 
```{ 'a': '%Y-%m-%d %H:%M:%S' } ```

**Comment by bsnacks000** [comment]
... OR maybe the user puts the column formatting dict on the defined serializer class. This is probably better, cause we can just have load_data do an auto lookup for date columns and call the time-format methods accordingly.

There's probably a way to even look up the formatting in the marshmallow _meta fields. I'll have to investigate that.

**Comment by bsnacks000** [comment]
#5

**Comment by bsnacks000** [comment]
This should now work with datetime.datetime, datetime.date objects when loading in records format. Dataframes with datetime64 cols will also be converted.

The utils parser method isn't checking specifically for numpy instances however so those and others might fail. We could compile a list of date objects we want converted but for now this will do.
